name: sky-run
resources:
  accelerators: T4:1
  cloud: aws
  region: us-east-2
workdir: .
file_mounts:
  ~/.ssh/id_rsa: ~/.ssh/id_rsa
  ~/.ssh/id_rsa.pub: ~/.ssh/id_rsa.pub
  ~/.gitconfig: ~/.gitconfig
setup: |
  pip install --upgrade pip
  pip install -r requirements.txt
  sudo add-apt-repository ppa:flexiondotorg/nvtop -y && sudo apt install nvtop
run: |
  cd ~/sky_workdir
  dvc pull
  dvc exp run --pull --allow-missing
  dvc exp push origin
  dvc push